// Android notification channels for per-account / per-room notification
// sounds.
//
// Android 8+ reality: a notification's sound (and importance/vibration) is a
// property of its NotificationChannel, fixed at channel-creation time — it
// cannot be changed per-notification, and an existing channel's sound can only
// be changed by the *user* in Android settings (or by recreating the channel
// under a new id). So "a different sound per account" and "a specific sound
// for this room" mean posting through dedicated channels:
//
//   - one channel per signed-in account:  acct.<accountKey>
//   - one channel per room override:      room.<accountKey>.<roomId>
//     (created only when the user sets a room-specific sound, so the OS
//     notification-settings list doesn't drown in one channel per room)
//
// The stock @tauri-apps/plugin-notification can only attach *bundled raw
// resource* sounds to a channel (it builds android.resource://<pkg>/raw/<name>
// URIs, see ChannelManager.kt). This app ships no raw audio resources —
// src-tauri/gen/android is regenerated by `tauri android init` on every CI
// build — so channels are created without an explicit sound and use the system
// default tone. The user still gets a real per-account / per-room sound choice
// today: Android Settings → Apps → Materix → Notifications lists each channel
// and offers the full system ringtone picker per channel.
//
// To ship our own tones (or honor the in-app SoundId picks at the OS level),
// CI must copy .ogg files into gen/android/app/src/main/res/raw after
// `tauri android init` (like the MainActivity keyboard patch) and this module
// can then pass `sound: "<raw name>"` at channel creation — note the sound is
// frozen at creation, so changing it later requires a versioned channel id.
// Arbitrary user-picked files (content:// via SAF) additionally need a small
// Kotlin patch to ChannelManager to accept non-resource URIs.

import { getPrefs, roomSoundKey } from "./prefs";

export const isTauri = typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
export const isAndroid =
  isTauri && typeof navigator !== "undefined" && /android/i.test(navigator.userAgent);

// Cache the dynamically-imported Tauri notification module so the web bundle
// never hard-depends on it and desktop/Android only load it once.
type TauriNotify = typeof import("@tauri-apps/plugin-notification");
let tauriMod: Promise<TauriNotify> | null = null;
export function loadTauriNotification(): Promise<TauriNotify> {
  if (!tauriMod) tauriMod = import("@tauri-apps/plugin-notification");
  return tauriMod;
}

export function accountChannelId(accountKey: string): string {
  return `acct.${accountKey}`;
}

export function roomChannelId(accountKey: string, roomId: string): string {
  return `room.${accountKey}.${roomId}`;
}

/** Channels ensured this session — createChannel is idempotent (it updates the
 * name/description of an existing id), so this only avoids repeat IPC. */
const ensured = new Set<string>();

async function createChannel(id: string, name: string, description: string): Promise<void> {
  const mod = await loadTauriNotification();
  await mod.createChannel({
    id,
    name,
    description,
    // High importance so message notifications heads-up over other apps.
    importance: mod.Importance.High,
    vibration: true,
  });
}

/** Idempotently create the per-account message channel. Android only; returns
 * the channel id, or null when unavailable (non-Android or plugin failure). */
export async function ensureAccountChannel(accountKey: string, label: string): Promise<string | null> {
  if (!isAndroid) return null;
  const id = accountChannelId(accountKey);
  if (!ensured.has(id)) {
    try {
      await createChannel(id, `Messages · ${label}`, `Message notifications for ${label}`);
      ensured.add(id);
    } catch (e) {
      console.warn("materix: creating account notification channel failed", e);
      return null;
    }
  }
  return id;
}

/** Idempotently create a dedicated channel for one room (per-room sound). */
export async function ensureRoomChannel(
  accountKey: string,
  roomId: string,
  roomLabel: string,
): Promise<string | null> {
  if (!isAndroid) return null;
  const id = roomChannelId(accountKey, roomId);
  if (!ensured.has(id)) {
    try {
      await createChannel(id, `Room · ${roomLabel}`, `Notifications for ${roomLabel}`);
      ensured.add(id);
    } catch (e) {
      console.warn("materix: creating room notification channel failed", e);
      return null;
    }
  }
  return id;
}

/** Delete a room's dedicated channel (when its sound override is cleared). */
export async function removeRoomChannel(accountKey: string, roomId: string): Promise<void> {
  if (!isAndroid) return;
  const id = roomChannelId(accountKey, roomId);
  ensured.delete(id);
  try {
    const { removeChannel } = await loadTauriNotification();
    await removeChannel(id);
  } catch {
    // Best effort; a stray channel is harmless.
  }
}

/** The channel a notification for this room should post through: the room's
 * own channel when the user set a room override, else the account channel,
 * else undefined (plugin's built-in "Default" channel). */
export async function channelFor(
  accountKey: string,
  accountLabel: string,
  roomId: string,
  roomLabel: string,
): Promise<string | undefined> {
  if (!isAndroid) return undefined;
  if (getPrefs().roomSounds[roomSoundKey(accountKey, roomId)] !== undefined) {
    const id = await ensureRoomChannel(accountKey, roomId, roomLabel);
    if (id) return id;
  }
  return (await ensureAccountChannel(accountKey, accountLabel)) ?? undefined;
}
