#!/usr/bin/env bash
# Inject the microphone/camera permission declarations for 1:1 WebRTC calls
# (and voice messages) into the (gitignored, regenerated) src-tauri/gen/android
# tree. Run AFTER `tauri android init` and BEFORE `tauri android build`.
# Idempotent — safe to run more than once.
#
# Why this is the whole fix: wry's RustWebChromeClient already implements
# WebChromeClient.onPermissionRequest — when the page calls getUserMedia() it
# launches the Android runtime-permission dialog and, on grant, approves the
# WebView's AUDIO_CAPTURE/VIDEO_CAPTURE resources. But Android auto-DENIES any
# runtime request for a permission that is not declared in the merged
# AndroidManifest, and the Tauri template declares none of these — so every
# getUserMedia() on Android failed instantly with NotAllowedError and calls
# never got a media stream (never rang / dropped immediately). Declaring the
# permissions here lets that existing plumbing work; the user-facing prompt
# still happens lazily, at first call / first voice recording.
#
# Same injection pattern as scripts/apply-android-push.sh (gen/android is
# regenerated by `tauri android init`, so nothing there can be committed).
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
app="$here/src-tauri/gen/android/app"

test -d "$app" || { echo "::error::gen/android not found — run 'tauri android init' first"; exit 1; }

python3 - "$app/src/main/AndroidManifest.xml" <<'PY'
import sys
p = sys.argv[1]; s = open(p).read()
if 'RECORD_AUDIO' in s:
    print("apply-android-av: AndroidManifest already patched"); sys.exit(0)
s = s.replace(
    '<uses-permission android:name="android.permission.INTERNET" />',
    '<uses-permission android:name="android.permission.INTERNET" />\n'
    '    <!-- 1:1 WebRTC calls + voice messages: getUserMedia() in the WebView.\n'
    '         The runtime prompt is raised lazily at call time by wry\'s\n'
    '         WebChromeClient.onPermissionRequest; declaring the permissions\n'
    '         here is what allows that request to be grantable at all\n'
    '         (undeclared runtime permissions are auto-denied by Android). -->\n'
    '    <uses-permission android:name="android.permission.RECORD_AUDIO" />\n'
    '    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />\n'
    '    <uses-permission android:name="android.permission.CAMERA" />\n'
    '    <!-- CAMERA/RECORD_AUDIO imply required hardware features; undo that so\n'
    '         camera-less or mic-less devices can still install Materix. -->\n'
    '    <uses-feature android:name="android.hardware.camera" android:required="false" />\n'
    '    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />\n'
    '    <uses-feature android:name="android.hardware.microphone" android:required="false" />',
    1)
assert 'RECORD_AUDIO' in s, "could not find the INTERNET uses-permission anchor in AndroidManifest.xml"
open(p, 'w').write(s)
print("apply-android-av: AndroidManifest patched (mic/camera call permissions)")
PY

echo "apply-android-av: done"
